apiVersion: v1
kind: Pod
metadata:
  name: simple-echo # Resorce name
spec:
  containers:
  - name: nginx # Container name [nginx]
    image: gihyodocker/nginx-proxy:latest # Container image
    env:
    - name: BACKEND_HOST # Proxy target host
      value: "http://localhost:8080"
    ports:
    - containerPort: 80
  - name: echo # Container name [echo]
    image: gihyodocker/echo:latest
    ports:
    - containerPort: 8080
